/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.course.model.impl;

import com.liferay.docs.course.model.Registration;
import com.liferay.docs.course.service.RegistrationLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Registration service. Represents a row in the &quot;registration_tbl&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationImpl}.
 * </p>
 *
 * @author to.trinh
 * @see RegistrationImpl
 * @see com.liferay.docs.course.model.Registration
 * @generated
 */
public abstract class RegistrationBaseImpl extends RegistrationModelImpl
	implements Registration {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration model instance should use the {@link Registration} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			RegistrationLocalServiceUtil.addRegistration(this);
		}
		else {
			RegistrationLocalServiceUtil.updateRegistration(this);
		}
	}
}